title: A example course for you to learn
tagline: >-
  Learn how to make courses on the course maker using a course. Realize that
  we'll use use app's name for creating the final files repo.
description: Here you might use some MD. Probably.
template:
  name: course-example
  repo: course-example-template
preferences:
  - type: dropdown
    name: language
    label: Language
    description: Choose your preferred language.
    options:
      - label: English
        value: en
      - label: Português
        value: pt
before:
  - body: hello-world.md
    title: Hello
    type: createIssue
steps:
  - title: Hello
    description: >-
      Description for the Hello World step (used solely for Github's progress
      page)
    translations:
      pt:
        title: Olá
        description: Descrição para o step de Hello World
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
      - body: writing-jsonc.md
        title: >-
          On this step, we have tests that check if some JSONC files were
          correctly made
        type: createIssue
  - title: >-
      On this step, we have tests that check if some JSONC files were correctly
      made
    description: Second description
    translations:
      pt:
        title: >-
          Neste passo teremos testes para verificar se alguns arquivos JSONC
          foram corretamente criados
        description: Segunda descrição
    event: status
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 2
        data:
          nextIssue: '3'
      - body: writing-css.md
        title: >-
          Here, we will get some CSS files and parse them, checking if the
          correct classes were declared
        type: createIssue
  - title: >-
      Here, we will get some CSS files and parse them, checking if the correct
      classes were declared
    description: Third description
    translations:
      pt:
        title: >-
          Aqui, iremos parsear arquivos CSS submetidos e verificar se as classes
          foram corretamente criadas
        description: Terceira descrição
    event: status
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 3
        data:
          nextIssue: '4'
      - body: wrapping-up.md
        title: Here you can set another title for this step
        type: createIssue
  - title: Here you can set another title for this step
    description: Every description is required for each step
    translations:
      pt:
        title: Aqui você pode colocar outro título para seu step
        description: O campo descrição é obrigatório para todo step
    event: status
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
